### ISSUE TITLE
invoice.create documentation example

### ISSUE THREAD

**Issue by drschwabe** [marcloney/freshbooks.js#17]
Was able to do invoice.get with help of the example, but I seem to be missing something with invoice.create.  It would be helpful if there was also an example for that. 

Either way, here is my attempt, and the subsequent error - if you know the problem, I would appreciate you to point it out.  Thanks. 

```
//Prepare a Freshbooks invoice...
var invoice = new freshbooks.Invoice()
var invoiceOpts = { //Fields as per Freshbooks API: 
  invoice: {
    first_name : first_name, 
    last_name : last_name, 
    p_street1 : address1, 
    p_city : city, 
    p_state : state,
    p_country: 'Canada', 
    p_code : postal, 
    lines : [{
      description : title, 
      quantity : 1, 
      unit_cost : ee, 
      tax1_name : 'GST', 
      tax1_percent : 5
    }]
  }
}
//create the invoice: 
invoice.create(invoiceOpts, function(err, freshBooksRes) {
  if(err) return console.log(err)
  console.log(freshBooksRes)
})
```
Results in the error: 
```
/home/derrick/myapp/node_modules/freshbooks/lib/Invoice.js:200
        fn(new Error("CANNOT CREATE INVOICE: " + err));
        ^

TypeError: fn is not a function
    at /home/derrick/myapp/node_modules/freshbooks/lib/Invoice.js:200:9
    at IncomingMessage.<anonymous> (/home/derrick/myapp/node_modules/freshbooks/lib/index.js:102:7)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

**Comment by drschwabe** [comment]
Eventually I learned that the way to do it is by modifying the initial invoice object, then pass that to itself via invoice.create - which seems odd, no?  Anyway, maybe we could add an extra example to the readme to cover this since it is a common use case.
